name: Release

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: "1.3.13"

      - run: bun install --frozen-lockfile --ignore-scripts
      - run: bun run build

      - run: bun run scripts/release.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Enable after configuring oidc
      # - run: npm publish --ignore-scripts
